server:
  error:
    include-message: always
    include-stacktrace: never

spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/turno
    password: postgres
    username: postgres
    driverClassName: org.postgresql.Driver